name: Build Qt Project on Windows

on:
  push:
    branches:
      - main   # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main   # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Qt
      uses: mkeeter/setup-qt@v2
      with:
        qt-version: '5.15.2'  # Specify the Qt version you want
        qt-arch: 'win64'      # Specify the architecture (win64 or win32)
        qt-additional-modules: 'qtbase'  # Specify Qt modules

    - name: Set up MSYS2 (required for building with qmake)
      run: |
        choco install msys2
        refreshenv
        pacman -Syu --noconfirm
        pacman -S --noconfirm base-devel mingw-w64-x86_64-toolchain

    - name: Install dependencies
      run: |
        pacman -S --noconfirm mingw-w64-x86_64-qt5

    - name: Configure and build project
      run: |
        qmake yourproject.pro  # Adjust path if necessary
        mingw32-make           # Compile the project

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: path/to/your/exe/yourapp.exe  # Adjust to the path where the .exe is built
