name: Build Qt Project on Windows

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - uses: actions/checkout@v3  # Use the latest version of actions/checkout

    # Install MSYS2 with MinGW
    - name: Set up MSYS2 with MinGW
      uses: msys2/setup-msys2@v2
      with:
        install: mingw-w64-x86_64-toolchain
        msystem: mingw64
        release: false

    # Install Qt 5.15.2 (via the jurplel/install-qt-action)
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.15.2'  # Specify version
        host: 'windows'
        target: 'desktop'
        arch: 'win64_mingw73'
        dir: '${{github.workspace}}/qt/'  # Qt directory
        install-deps: 'true'  # Install necessary dependencies

    - name: List files in Qt directory
      run: find ${{env.Qt5_Dir}}  # List the files to confirm installation

    # Configure the project using qmake
    - name: Configure with qmake
      run: |
        $env:PATH += ";${{github.workspace}}/qt/5.15.2/mingw73_64/bin"
        qmake better-browser.pro  # Replace with your .pro file path

    # Build the project with mingw32-make
    - name: Build with mingw32-make
      run: |
        mingw32-make

    # Upload the build artifact (exe)
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4  # Make sure you're using the latest version
      with:
        name: build-artifact
        path: better-browser.exe  # Adjust the path if necessary
