name: Build Qt Project on Windows

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download Qt online installer
      run: |
        # Download the Qt Online Installer (no version specified, latest available)
        Invoke-WebRequest -Uri "https://download.qt.io/official_releases/qt/5.15/qt-opensource-windows-x86-5.15.2.exe" -OutFile "qt-installer.exe"

    - name: Install Qt silently
      run: |
        # Run the installer in headless mode (no UI)
        Start-Process -NoNewWindow -FilePath "qt-installer.exe" -ArgumentList "/S" -Wait

    - name: Set up environment for Qt
      run: |
        # Set up environment variables for Qt (adjust this if needed)
        $env:PATH += ";C:\Qt\5.15.2\msvc2019_64\bin"  # You may need to change this path if different
        
        # Verify Qt installation
        qmake -v

    - name: Install MinGW via Chocolatey
      run: |
        choco install mingw
        refreshenv  # Refresh environment variables to detect MinGW installation

    - name: Configure and build project
      run: |
        qmake better-browser.pro  # Adjust path if necessary
        mingw32-make           # Compile the project

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: build-artifact
        path: better-browser.exe  # Adjust to the path where the .exe is built
