name: Build Qt Project on Windows

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Qt via Chocolatey
      run: |
        choco install qt5 --version=5.15.2 --install-arguments 'ADD_EXAMPLES=0 ADD_DOC=0'  # Specify version of Qt you need
        refreshenv  # Refresh environment variables to detect Qt installation

    - name: Install build tools (MinGW)
      run: |
        choco install mingw
        refreshenv  # Refresh environment variables to detect MinGW installation

    - name: Configure and build project
      run: |
        qmake better-browser.pro  # Adjust path if necessary
        mingw32-make           # Compile the project

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3  # Updated to v3
      with:
        name: build-artifact
        path: better-browser.exe  # Adjust to the path where the .exe is built
